name: Supervised Classification, features: sick
{'X_train': {'cols': 0.013897296206618242, 'rows': 0.2055084745762712}, 'X_valid': {'cols': 0.012980898574118912, 'rows': 0.19868173258003766}, 'X_test': {'cols': 0.02109528859263748, 'rows': 0.28207847295864263}}
dataset sizes
(4254, 28) (1062, 28) (943, 28)
dropped dataset sizes
(3381, 28) (851, 28) (677, 28)
key: 6238, k: 1/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 36, 'max_bin': 236, 'max_depth': 20, 'min_data_in_leaf': 13, 'learning_rate': 0.020225911240896222, 'num_iterations': 455, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Early stopping, best iteration is:
[333]	valid_0's multi_logloss: 0.00385798
strategy:None, acc gbm: 0.9883351007423118
strategy:None, nll xbg:0.07341574132442474
name: Supervised Classification, features: sick
{'X_train': {'cols': 0.013724633785781482, 'rows': 0.19637817497648166}, 'X_valid': {'cols': 0.013392857142857142, 'rows': 0.19454887218045114}, 'X_test': {'cols': 0.020565065899106196, 'rows': 0.29056203605514314}}
dataset sizes
(4278, 28) (1064, 28) (943, 28)
dropped dataset sizes
(3439, 28) (857, 28) (669, 28)
key: 4168, k: 2/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 36, 'max_bin': 236, 'max_depth': 20, 'min_data_in_leaf': 13, 'learning_rate': 0.020225911240896222, 'num_iterations': 455, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Early stopping, best iteration is:
[285]	valid_0's multi_logloss: 0.0114377
strategy:None, acc gbm: 0.9872746553552492
strategy:None, nll xbg:0.06377600878477097
name: Supervised Classification, features: sick
{'X_train': {'cols': 0.013003018108651912, 'rows': 0.18708920187793426}, 'X_valid': {'cols': 0.01232913428035379, 'rows': 0.18761726078799248}, 'X_test': {'cols': 0.02238297227692774, 'rows': 0.3149522799575822}}
dataset sizes
(4280, 28) (1066, 28) (943, 28)
dropped dataset sizes
(3478, 28) (866, 28) (646, 28)
key: 9559, k: 3/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 36, 'max_bin': 236, 'max_depth': 20, 'min_data_in_leaf': 13, 'learning_rate': 0.020225911240896222, 'num_iterations': 455, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[261]	valid_0's multi_logloss: 0.0173078
strategy:None, acc gbm: 0.9830328738069989
strategy:None, nll xbg:0.12698282301425934
name: Supervised Classification, features: sick
{'X_train': {'cols': 0.013172541743970314, 'rows': 0.19811097992916174}, 'X_valid': {'cols': 0.0150748684743019, 'rows': 0.210576015108593}, 'X_test': {'cols': 0.022761702772307223, 'rows': 0.30965005302226933}}
dataset sizes
(4284, 28) (1059, 28) (943, 28)
dropped dataset sizes
(3427, 28) (836, 28) (651, 28)
key: 7086, k: 4/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 36, 'max_bin': 236, 'max_depth': 20, 'min_data_in_leaf': 13, 'learning_rate': 0.020225911240896222, 'num_iterations': 455, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[409]	valid_0's multi_logloss: 0.0109117
strategy:None, acc gbm: 0.9925768822905621
strategy:None, nll xbg:0.0449792854487896