name: Supervised Regression, features: us_crime
{'X_train': {'cols': 0.1564474173169826, 'rows': 0.9389632107023411}, 'X_valid': {'cols': 0.15182884748102132, 'rows': 0.9331103678929766}, 'X_test': {'cols': 0.15755320164137798, 'rows': 0.9398797595190381}}
dataset sizes
(1196, 126) (299, 126) (499, 126)
dropped dataset sizes
(73, 126) (20, 126) (30, 126)
key: 7383, k: 1/4, dataset: 42730, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 17, 'max_bin': 19, 'max_depth': 31, 'min_data_in_leaf': 24, 'learning_rate': 8.741553009537878e-05, 'num_iterations': 926, 'objective': 'regression', 'verbose': -1, 'num_class': 1}
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[926]	valid_0's l2: 0.980577
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/basic.py:179: UserWarning: Converting column-vector to 1d array
  _log_warning('Converting column-vector to 1d array')
Traceback (most recent call last):
  File "/home/jahan/Missingness/train.py", line 143, in <module>
    metrics_df, perc_missing = run(
  File "/home/jahan/Missingness/benchmarkaux/openmlrun.py", line 225, in run
    wandb.log({"gbm_rmse_fold{}".format(count):rmse}, commit=False)
UnboundLocalError: local variable 'rmse' referenced before assignment