name: Supervised Classification, features: sick
{'X_train': {'cols': 0.01384685230024213, 'rows': 0.20951035781544255}, 'X_valid': {'cols': 0.013518966908797416, 'rows': 0.1911487758945386}, 'X_test': {'cols': 0.02109528859263748, 'rows': 0.28207847295864263}}
dataset sizes
(4304, 28) (1062, 28) (943, 28)
dropped dataset sizes
(3396, 28) (859, 28) (677, 28)
key: 7981, k: 1/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 35, 'max_bin': 188, 'max_depth': 7, 'min_data_in_leaf': 15, 'learning_rate': 0.058330434029143285, 'num_iterations': 177, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[93]	valid_0's multi_logloss: 0.0272865
strategy:None, acc gbm: 0.9862142099681867
strategy:None, nll xbg:0.08834120631217957
name: Supervised Classification, features: sick
{'X_train': {'cols': 0.01338865743851633, 'rows': 0.19308560677328315}, 'X_valid': {'cols': 0.014634801288936626, 'rows': 0.20582706766917294}, 'X_test': {'cols': 0.020565065899106196, 'rows': 0.29056203605514314}}
dataset sizes
(4276, 28) (1064, 28) (943, 28)
dropped dataset sizes
(3450, 28) (845, 28) (669, 28)
key: 6360, k: 2/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 35, 'max_bin': 188, 'max_depth': 7, 'min_data_in_leaf': 15, 'learning_rate': 0.058330434029143285, 'num_iterations': 177, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[114]	valid_0's multi_logloss: 0.00495936
strategy:None, acc gbm: 0.9915164369034994
strategy:None, nll xbg:0.05083600804209709
name: Supervised Classification, features: sick
{'X_train': {'cols': 0.013120389000670692, 'rows': 0.1892018779342723}, 'X_valid': {'cols': 0.012463146609488074, 'rows': 0.18574108818011256}, 'X_test': {'cols': 0.02238297227692774, 'rows': 0.3149522799575822}}
dataset sizes
(4266, 28) (1066, 28) (943, 28)
dropped dataset sizes
(3459, 28) (868, 28) (646, 28)
key: 1349, k: 3/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 35, 'max_bin': 188, 'max_depth': 7, 'min_data_in_leaf': 15, 'learning_rate': 0.058330434029143285, 'num_iterations': 177, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[108]	valid_0's multi_logloss: 0.00859821
strategy:None, acc gbm: 0.9872746553552492
strategy:None, nll xbg:0.10737606883049011
name: Supervised Classification, features: sick
{'X_train': {'cols': 0.013973688649013324, 'rows': 0.2014167650531287}, 'X_valid': {'cols': 0.012478079050317012, 'rows': 0.1964117091595845}, 'X_test': {'cols': 0.022761702772307223, 'rows': 0.30965005302226933}}
dataset sizes
(4266, 28) (1059, 28) (943, 28)
dropped dataset sizes
(3407, 28) (851, 28) (651, 28)
key: 262, k: 4/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 35, 'max_bin': 188, 'max_depth': 7, 'min_data_in_leaf': 15, 'learning_rate': 0.058330434029143285, 'num_iterations': 177, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[130]	valid_0's multi_logloss: 0.00865898
strategy:None, acc gbm: 0.9925768822905621
strategy:None, nll xbg:0.04673031345009804
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")