name: Supervised Classification, features: sick
{'X_train': {'cols': 0.013796408393866021, 'rows': 0.20268361581920905}, 'X_valid': {'cols': 0.012577347323110033, 'rows': 0.19397363465160075}, 'X_test': {'cols': 0.02109528859263748, 'rows': 0.28207847295864263}}
dataset sizes
(4276, 28) (1062, 28) (943, 28)
dropped dataset sizes
(3410, 28) (856, 28) (677, 28)
key: 4007, k: 1/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 21, 'max_bin': 196, 'max_depth': 29, 'min_data_in_leaf': 19, 'learning_rate': 0.008979523502238004, 'num_iterations': 703, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[703]	valid_0's multi_logloss: 0.0181922
strategy:None, acc gbm: 0.9862142099681867
strategy:None, nll xbg:0.07631255686283112
name: Supervised Classification, features: sick
{'X_train': {'cols': 0.013691036151054966, 'rows': 0.19614299153339604}, 'X_valid': {'cols': 0.01342642320085929, 'rows': 0.20300751879699247}, 'X_test': {'cols': 0.020565065899106196, 'rows': 0.29056203605514314}}
dataset sizes
(4296, 28) (1064, 28) (943, 28)
dropped dataset sizes
(3443, 28) (848, 28) (669, 28)
key: 9512, k: 2/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 21, 'max_bin': 196, 'max_depth': 29, 'min_data_in_leaf': 19, 'learning_rate': 0.008979523502238004, 'num_iterations': 703, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[695]	valid_0's multi_logloss: 0.0151866
strategy:None, acc gbm: 0.985153764581124
strategy:None, nll xbg:0.07840893417596817
name: Supervised Classification, features: sick
{'X_train': {'cols': 0.012894030851777332, 'rows': 0.18779342723004694}, 'X_valid': {'cols': 0.013099705172875906, 'rows': 0.18855534709193245}, 'X_test': {'cols': 0.02238297227692774, 'rows': 0.3149522799575822}}
dataset sizes
(4274, 28) (1066, 28) (943, 28)
dropped dataset sizes
(3474, 28) (865, 28) (646, 28)
key: 3493, k: 3/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 21, 'max_bin': 196, 'max_depth': 29, 'min_data_in_leaf': 19, 'learning_rate': 0.008979523502238004, 'num_iterations': 703, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[703]	valid_0's multi_logloss: 0.0135524
strategy:None, acc gbm: 0.9893955461293743
strategy:None, nll xbg:0.07979211211204529
name: Supervised Classification, features: sick
{'X_train': {'cols': 0.013973688649013325, 'rows': 0.20354191263282173}, 'X_valid': {'cols': 0.012410629974369352, 'rows': 0.1954674220963173}, 'X_test': {'cols': 0.022761702772307223, 'rows': 0.30965005302226933}}
dataset sizes
(4248, 28) (1059, 28) (943, 28)
dropped dataset sizes
(3381, 28) (852, 28) (651, 28)
key: 1651, k: 4/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 21, 'max_bin': 196, 'max_depth': 29, 'min_data_in_leaf': 19, 'learning_rate': 0.008979523502238004, 'num_iterations': 703, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[624]	valid_0's multi_logloss: 0.0243649
strategy:None, acc gbm: 0.9904559915164369
strategy:None, nll xbg:0.06278827786445618