name: Supervised Regression, features: SAT11-HAND-runtime-regression
{'X_train': {'cols': 0.0525849124987056, 'rows': 0.609984984984985}, 'X_valid': {'cols': 0.05268199233716476, 'rows': 0.6111111111111112}, 'X_test': {'cols': 0.05304442373407891, 'rows': 0.6153153153153154}}
dataset sizes
(2664, 116) (666, 116) (1110, 116)
dropped dataset sizes
(1039, 116) (259, 116) (427, 116)
key: 9845, k: 1/4, dataset: 41980, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 14, 'max_bin': 71, 'max_depth': 4, 'min_data_in_leaf': 29, 'learning_rate': 0.2831689859574845, 'num_iterations': 125, 'objective': 'regression', 'verbose': -1, 'num_class': 1}
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[121]	valid_0's l2: 0.265053
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/basic.py:179: UserWarning: Converting column-vector to 1d array
  _log_warning('Converting column-vector to 1d array')
Traceback (most recent call last):
  File "/home/jahan/Missingness/train.py", line 143, in <module>
    metrics_df, perc_missing = run(
  File "/home/jahan/Missingness/benchmarkaux/openmlrun.py", line 225, in run
    wandb.log({"gbm_rmse_fold{}".format(count):rmse}, commit=False)
UnboundLocalError: local variable 'rmse' referenced before assignment