/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Traceback (most recent call last):
  File "/home/jahan/Missingness/train.py", line 141, in <module>
    metrics_df, perc_missing = run(
  File "/home/jahan/Missingness/benchmarkaux/openmlrun.py", line 229, in run
    wandb.log({"gbm_nll_fold{}".format(count):nll}, commit=False)
UnboundLocalError: local variable 'nll' referenced before assignment
name: Supervised Classification, features: dresses-sales
{'X_train': {'cols': 0.1396072796934866, 'rows': 0.8074712643678161}, 'X_valid': {'cols': 0.13162878787878787, 'rows': 0.7840909090909091}, 'X_test': {'cols': 0.14733333333333334, 'rows': 0.8}}
dataset sizes
(348, 12) (88, 12) (125, 12)
dropped dataset sizes
(67, 12) (19, 12) (25, 12)
key: 4006, k: 1/4, dataset: 23381, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 3, 'max_bin': 101, 'max_depth': 2, 'min_data_in_leaf': 4, 'learning_rate': 7, 'num_iterations': 4, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1]	valid_0's multi_logloss: 1.59765
strategy:None, acc gbm: 0.584