name: Supervised Classification, features: eucalyptus
{'X_train': {'cols': 0.028798411122144985, 'rows': 0.12106918238993711}, 'X_valid': {'cols': 0.027143330023171135, 'rows': 0.09433962264150944}, 'X_test': {'cols': 0.03175057208237986, 'rows': 0.1358695652173913}}
dataset sizes
(660, 19) (159, 19) (184, 19)
dropped dataset sizes
(581, 19) (144, 19) (159, 19)
key: 3269, k: 1/4, dataset: 188, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 28, 'max_bin': 133, 'max_depth': 29, 'min_data_in_leaf': 11, 'learning_rate': 0.007679022417884354, 'num_iterations': 304, 'objective': 'softmax', 'verbose': -1, 'num_class': 5}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[304]	valid_0's multi_logloss: 0.545449
strategy:None, acc gbm: 0.6141304347826086
strategy:None, nll xbg:0.8882176280021667
name: Supervised Classification, features: eucalyptus
{'X_train': {'cols': 0.024599542334096107, 'rows': 0.11024844720496894}, 'X_valid': {'cols': 0.030402092186989218, 'rows': 0.13664596273291926}, 'X_test': {'cols': 0.028318077803203664, 'rows': 0.11413043478260869}}
dataset sizes
(660, 19) (161, 19) (184, 19)
dropped dataset sizes
(589, 19) (139, 19) (163, 19)
key: 8480, k: 2/4, dataset: 188, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 28, 'max_bin': 133, 'max_depth': 29, 'min_data_in_leaf': 11, 'learning_rate': 0.007679022417884354, 'num_iterations': 304, 'objective': 'softmax', 'verbose': -1, 'num_class': 5}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[304]	valid_0's multi_logloss: 0.569261
strategy:None, acc gbm: 0.6413043478260869
strategy:None, nll xbg:0.8853280544281006
name: Supervised Classification, features: eucalyptus
{'X_train': {'cols': 0.029813457694870087, 'rows': 0.125}, 'X_valid': {'cols': 0.019986675549633574, 'rows': 0.08227848101265822}, 'X_test': {'cols': 0.02974828375286041, 'rows': 0.11956521739130435}}
dataset sizes
(655, 19) (158, 19) (184, 19)
dropped dataset sizes
(570, 19) (145, 19) (162, 19)
key: 3365, k: 3/4, dataset: 188, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 28, 'max_bin': 133, 'max_depth': 29, 'min_data_in_leaf': 11, 'learning_rate': 0.007679022417884354, 'num_iterations': 304, 'objective': 'softmax', 'verbose': -1, 'num_class': 5}
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[304]	valid_0's multi_logloss: 0.704741
strategy:None, acc gbm: 0.5869565217391305
strategy:None, nll xbg:0.9863401055335999
name: Supervised Classification, features: eucalyptus
{'X_train': {'cols': 0.027198331193838257, 'rows': 0.1173780487804878}, 'X_valid': {'cols': 0.016367137355584083, 'rows': 0.06707317073170732}, 'X_test': {'cols': 0.03832951945080091, 'rows': 0.14673913043478262}}
dataset sizes
(700, 19) (164, 19) (184, 19)
dropped dataset sizes
(622, 19) (153, 19) (157, 19)
key: 6231, k: 4/4, dataset: 188, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 28, 'max_bin': 133, 'max_depth': 29, 'min_data_in_leaf': 11, 'learning_rate': 0.007679022417884354, 'num_iterations': 304, 'objective': 'softmax', 'verbose': -1, 'num_class': 5}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[304]	valid_0's multi_logloss: 0.496118
strategy:None, acc gbm: 0.592391304347826
strategy:None, nll xbg:0.9355097413063049