name: Supervised Classification, features: sick
{'X_train': {'cols': 0.013510559591068064, 'rows': 0.20080037664783426}, 'X_valid': {'cols': 0.013249932741458165, 'rows': 0.2080979284369115}, 'X_test': {'cols': 0.02109528859263748, 'rows': 0.28207847295864263}}
dataset sizes
(4252, 28) (1062, 28) (943, 28)
dropped dataset sizes
(3398, 28) (841, 28) (677, 28)
key: 8493, k: 1/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 32, 'max_bin': 165, 'max_depth': 31, 'min_data_in_leaf': 26, 'learning_rate': 0.09909328000196356, 'num_iterations': 396, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[61]	valid_0's multi_logloss: 0.0275405
strategy:None, acc gbm: 0.985153764581124
strategy:None, nll xbg:0.10019432753324509
name: Supervised Classification, features: sick
{'X_train': {'cols': 0.013497849751377505, 'rows': 0.19308560677328315}, 'X_valid': {'cols': 0.014433404940923737, 'rows': 0.21334586466165414}, 'X_test': {'cols': 0.020565065899106196, 'rows': 0.29056203605514314}}
dataset sizes
(4252, 28) (1064, 28) (943, 28)
dropped dataset sizes
(3431, 28) (837, 28) (669, 28)
key: 5730, k: 2/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 32, 'max_bin': 165, 'max_depth': 31, 'min_data_in_leaf': 26, 'learning_rate': 0.09909328000196356, 'num_iterations': 396, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Early stopping, best iteration is:
[114]	valid_0's multi_logloss: 0.00781905
strategy:None, acc gbm: 0.9883351007423118
strategy:None, nll xbg:0.09733717888593674
name: Supervised Classification, features: sick
{'X_train': {'cols': 0.012659289067739773, 'rows': 0.18333333333333332}, 'X_valid': {'cols': 0.012764674350040205, 'rows': 0.1848030018761726}, 'X_test': {'cols': 0.02238297227692774, 'rows': 0.3149522799575822}}
dataset sizes
(4310, 28) (1066, 28) (943, 28)
dropped dataset sizes
(3524, 28) (869, 28) (646, 28)
key: 328, k: 3/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 32, 'max_bin': 165, 'max_depth': 31, 'min_data_in_leaf': 26, 'learning_rate': 0.09909328000196356, 'num_iterations': 396, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[100]	valid_0's multi_logloss: 0.00845672
strategy:None, acc gbm: 0.9883351007423118
strategy:None, nll xbg:0.10336177051067352
name: Supervised Classification, features: sick
{'X_train': {'cols': 0.01361106426041491, 'rows': 0.19716646989374262}, 'X_valid': {'cols': 0.013017671657898288, 'rows': 0.20585457979225685}, 'X_test': {'cols': 0.022761702772307223, 'rows': 0.30965005302226933}}
dataset sizes
(4274, 28) (1059, 28) (943, 28)
dropped dataset sizes
(3430, 28) (841, 28) (651, 28)
key: 8983, k: 4/4, dataset: 38, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 32, 'max_bin': 165, 'max_depth': 31, 'min_data_in_leaf': 26, 'learning_rate': 0.09909328000196356, 'num_iterations': 396, 'objective': 'softmax', 'verbose': -1, 'num_class': 2}
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[158]	valid_0's multi_logloss: 0.00661834
strategy:None, acc gbm: 0.9946977730646872
strategy:None, nll xbg:0.0439407117664814
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")