name: Supervised Classification, features: MiceProtein
{'X_train': {'cols': 0.01524949673097821, 'rows': 0.47599451303155005}, 'X_valid': {'cols': 0.016606344475196936, 'rows': 0.44808743169398907}, 'X_test': {'cols': 0.018518518518518517, 'rows': 0.5222222222222223}}
dataset sizes
(792, 77) (183, 77) (270, 77)
dropped dataset sizes
(416, 77) (101, 77) (129, 77)
key: 1654, k: 1/4, dataset: 40966, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 8, 'max_bin': 17, 'max_depth': 18, 'min_data_in_leaf': 12, 'learning_rate': 0.05669953848057918, 'num_iterations': 456, 'objective': 'softmax', 'verbose': -1, 'num_class': 8}
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[181]	valid_0's multi_logloss: 0.0661813
strategy:None, acc gbm: 0.9925925925925926
strategy:None, nll xbg:0.016852911561727524
name: Supervised Classification, features: MiceProtein
{'X_train': {'cols': 0.01743186391073715, 'rows': 0.48169014084507045}, 'X_valid': {'cols': 0.017583540055450167, 'rows': 0.5}, 'X_test': {'cols': 0.014718614718614718, 'rows': 0.48148148148148145}}
dataset sizes
(752, 77) (178, 77) (270, 77)
dropped dataset sizes
(394, 77) (89, 77) (140, 77)
key: 9129, k: 2/4, dataset: 40966, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 8, 'max_bin': 17, 'max_depth': 18, 'min_data_in_leaf': 12, 'learning_rate': 0.05669953848057918, 'num_iterations': 456, 'objective': 'softmax', 'verbose': -1, 'num_class': 8}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[456]	valid_0's multi_logloss: 0.0136112
strategy:None, acc gbm: 0.9851851851851852
strategy:None, nll xbg:0.03779665380716324
name: Supervised Classification, features: MiceProtein
{'X_train': {'cols': 0.01614148125776033, 'rows': 0.4728682170542636}, 'X_valid': {'cols': 0.014861427232561251, 'rows': 0.4793814432989691}, 'X_test': {'cols': 0.017075517075517074, 'rows': 0.4703703703703704}}
dataset sizes
(832, 77) (194, 77) (270, 77)
dropped dataset sizes
(443, 77) (101, 77) (143, 77)
key: 5337, k: 3/4, dataset: 40966, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 8, 'max_bin': 17, 'max_depth': 18, 'min_data_in_leaf': 12, 'learning_rate': 0.05669953848057918, 'num_iterations': 456, 'objective': 'softmax', 'verbose': -1, 'num_class': 8}
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[435]	valid_0's multi_logloss: 0.0531426
strategy:None, acc gbm: 0.9814814814814815
strategy:None, nll xbg:0.0770188495516777
name: Supervised Classification, features: MiceProtein
{'X_train': {'cols': 0.017539525691699604, 'rows': 0.49728260869565216}, 'X_valid': {'cols': 0.014751552795031056, 'rows': 0.4782608695652174}, 'X_test': {'cols': 0.01683501683501683, 'rows': 0.48148148148148145}}
dataset sizes
(768, 77) (184, 77) (270, 77)
dropped dataset sizes
(387, 77) (96, 77) (140, 77)
key: 8494, k: 4/4, dataset: 40966, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 8, 'max_bin': 17, 'max_depth': 18, 'min_data_in_leaf': 12, 'learning_rate': 0.05669953848057918, 'num_iterations': 456, 'objective': 'softmax', 'verbose': -1, 'num_class': 8}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Early stopping, best iteration is:
[282]	valid_0's multi_logloss: 0.0135983
strategy:None, acc gbm: 0.9925925925925926
strategy:None, nll xbg:0.03589925169944763