name: Supervised Classification, features: MiceProtein
{'X_train': {'cols': 0.015605793383571162, 'rows': 0.448559670781893}, 'X_valid': {'cols': 0.015257966077638208, 'rows': 0.5136612021857924}, 'X_test': {'cols': 0.018518518518518517, 'rows': 0.5222222222222223}}
dataset sizes
(752, 77) (183, 77) (270, 77)
dropped dataset sizes
(416, 77) (89, 77) (129, 77)
key: 9921, k: 1/4, dataset: 40966, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 8, 'max_bin': 11, 'max_depth': 29, 'min_data_in_leaf': 16, 'learning_rate': 0.014375020388800563, 'num_iterations': 437, 'objective': 'softmax', 'verbose': -1, 'num_class': 8}
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[437]	valid_0's multi_logloss: 0.0334469
strategy:None, acc gbm: 0.9740740740740741
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
strategy:None, nll xbg:0.06683050096035004
name: Supervised Classification, features: MiceProtein
{'X_train': {'cols': 0.016992866288640933, 'rows': 0.4915492957746479}, 'X_valid': {'cols': 0.01933459798628338, 'rows': 0.449438202247191}, 'X_test': {'cols': 0.014718614718614718, 'rows': 0.48148148148148145}}
dataset sizes
(784, 77) (178, 77) (270, 77)
dropped dataset sizes
(400, 77) (98, 77) (140, 77)
key: 5700, k: 2/4, dataset: 40966, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 8, 'max_bin': 11, 'max_depth': 29, 'min_data_in_leaf': 16, 'learning_rate': 0.014375020388800563, 'num_iterations': 437, 'objective': 'softmax', 'verbose': -1, 'num_class': 8}
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[437]	valid_0's multi_logloss: 0.0266964
strategy:None, acc gbm: 0.9888888888888889
strategy:None, nll xbg:0.04601879045367241
name: Supervised Classification, features: MiceProtein
{'X_train': {'cols': 0.01622537669049297, 'rows': 0.4728682170542636}, 'X_valid': {'cols': 0.016267237916722452, 'rows': 0.5103092783505154}, 'X_test': {'cols': 0.017075517075517074, 'rows': 0.4703703703703704}}
dataset sizes
(800, 77) (194, 77) (270, 77)
dropped dataset sizes
(421, 77) (95, 77) (143, 77)
key: 2003, k: 3/4, dataset: 40966, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 8, 'max_bin': 11, 'max_depth': 29, 'min_data_in_leaf': 16, 'learning_rate': 0.014375020388800563, 'num_iterations': 437, 'objective': 'softmax', 'verbose': -1, 'num_class': 8}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[437]	valid_0's multi_logloss: 0.0244974
strategy:None, acc gbm: 0.9888888888888889
strategy:None, nll xbg:0.05837462097406387
name: Supervised Classification, features: MiceProtein
{'X_train': {'cols': 0.015386787125917564, 'rows': 0.4701086956521739}, 'X_valid': {'cols': 0.01948051948051948, 'rows': 0.5217391304347826}, 'X_test': {'cols': 0.01683501683501683, 'rows': 0.48148148148148145}}
dataset sizes
(808, 77) (184, 77) (270, 77)
dropped dataset sizes
(424, 77) (88, 77) (140, 77)
key: 3116, k: 4/4, dataset: 40966, missing: None, impute: None
training gbm for 5000 epochs
{'num_leaves': 8, 'max_bin': 11, 'max_depth': 29, 'min_data_in_leaf': 16, 'learning_rate': 0.014375020388800563, 'num_iterations': 437, 'objective': 'softmax', 'verbose': -1, 'num_class': 8}
Training until validation scores don't improve for 100 rounds
/home/jahan/.conda/envs/jax/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
Did not meet early stopping. Best iteration is:
[437]	valid_0's multi_logloss: 0.0490409
strategy:None, acc gbm: 0.9814814814814815
strategy:None, nll xbg:0.0866614431142807